### ISSUE TITLE
Question - does it support multi-node cluster?

### ISSUE THREAD

**Issue by aidanbon** [team-emt/razorframe#61]
Just reading up the top-level doc and haven't tried out or dug into the code yet.

Does razorframe support multi-node cluster environment (e.g. behind a load balancer), in addition to utilizing multiple CPUs within a single node?

Thanks!

**Comment by parkedwards** [comment]
We're planning on integrating with a multi-server architecture implementation, potentially one that utilizes Docker, Kubernetes, and a nginx load balancer.  However, razorframe is currently a solution for a single-server scaling for real-time
